### ISSUE TITLE
关于代码的一点疑惑

### ISSUE THREAD

**Issue by duqingnian** [FengJungle/QtSocket#1]
1.在QtSocket/QtSocketClient/QtSocketClient/Client.cpp 中，有一行代码：
connect(fileSocket, SIGNAL(bytesWritten(qint64)), this, SLOT(updateFileProgress(qint64)));
这里，socket没有bytesWritten这个信号吧？而且，updateFileProgress 这个也没在头文件中声明为slot

**Comment by FengJungle** [comment]
> 
Hello, 
First of all, bytesWritten(qint64), this signal is officially provided. 
I'm not sure if the second problem is a real issue. If it does cause some error, you'd better add a 'slot' declaration. 
Thanks, my friend.

**Comment by duqingnian** [comment]
well, first, Thank you for response my question. it's very helpful for me.
and, I thought you were Chinese, so I use chinese text to post this question. and thank you again.
I am writing a client using Qt, this client is send files using qtcpsocket, the file's size may 1kb,or 20Gb,the size is not sure.
but I am down this work.
and I am tested my program, It's run perfect.
Thank you my friend.
